### ISSUE TITLE
Clear old notifications

### ISSUE THREAD

**Issue by kymetro9999** [gdpelican/babble#70] opened 2015-10-25 03:42 UTC
Currently a user who logs in infrequently will see a count of all the chats since they last logged in. This can be in the hundreds... This is a meaningless and intimidating number to a user who hasn't discovered the feature yet.

Even when they finally view the chat window, they can only see the last 20 or so chat messages. The last post might be several days old. Telling them about hundreds of unviewable and/or stale messages is pointless.

I propose to clear all chat notifications older than 24 hours. This will prevent a buildup over time.

Alternatively, reset the counter to zero when the user logs in after a long time gone. Then when a "1" appears, it will make a visual impact.

**Comment by gdpelican** [comment] 2015-10-25 12:41
Duly noted, thanks!

**Comment by JSey** [comment] 2015-10-25 13:41
Kind of a dupe of #57. Maybe I can try to send a PR for this… let me check.

**Comment by gdpelican** [comment] 2015-11-21 21:28
This should be handled in #84

**Closed by gdpelican** 2015-11-21 21:28 UTC
