### ISSUE TITLE
Babble composer already active or could not be found

### ISSUE THREAD

**Issue by jorgtron** [gdpelican/babble#219] opened 2017-03-04 20:13 UTC
I've just updated to the latest version of Discourse and Babble, and am seeing some weird behavior.

On the home page, I can open the chat, type stuff and it gets sent and shown.
If I go into a topic while the chat is open and try to type I get errors like this:

![image](https://cloud.githubusercontent.com/assets/544631/23581931/11065c74-011f-11e7-9fa9-28f21e684034.png)

I've also seen this error at random times when attempting to open or close the chat while on a topic page:

![image](https://cloud.githubusercontent.com/assets/544631/23581938/3ebb90da-011f-11e7-9655-9a8ccb77048a.png)

This happens on desktop / Chrome / all browsers.

**Comment by ivissie** [comment] 2017-03-10 07:09
I also experience the same issue.

![image](https://cloud.githubusercontent.com/assets/4920420/23785606/3e02ac04-0571-11e7-9882-6fe034da4f72.png)

**Comment by gdpelican** [comment] 2017-03-10 21:15
Hrrrm. I haven't been able to repro any of this, although that warning has appeared intermittently for me, 

Steps I've taken:

- Go to the root path
- Open the shoutbox by clicking on the icon
- clicking on a topic title in the topic list
- Chat stays open, works as intended

Also
- Go to the root path
- Open the shoutbox by clicking on the icon
- clicking on the profile picture
- Chat closes, profile menu opens as expected

I can reproduce the warning as follows:
- Go to the chat path (/chat/category/925)
- Open the shoutbox by clicking on the icon
- Use the hamburger menu within the chat to switch to chat displayed in the full page chat

But it doesn't seem to cause any negative functionality that I can see.

What else should I try? Is someone able to make a gif of the steps they took?

**Comment by jorgtron** [comment] 2017-03-11 20:37
@gdpelican: I've made a screen recording: https://www.dropbox.com/s/uo2magv0f7y12qv/babble.mov?dl=0

I haven't tried the plugin on a fresh Discourse install yet, but I've tried disabling all other plugins and all site customisations, and deleted the cache - but still get the errors seen in the clip.

**Comment by jorgtron** [comment] 2017-03-21 13:59
Any ideas on what I can try to fix this? Could there be something cached somewhere since I've used Babble for a long time that would get messed up when updating it a bunch of times? #graspingatstraws

**Comment by jorgtron** [comment] 2017-03-21 13:59
Do you still have the same issue @ivissie? :)

**Comment by JSey** [comment] 2017-03-21 20:26
Maybe I narrowed it down today. I made a little recording of my findings here:

http://recordit.co/Mu4iMK8r8e

Repro on Safari, Chrome and Firefox (all recent). The problem only starts when the  Discourse header changes after scrolling into a topic by adding the ```extra-info-wrapper``` div (which displays the topic title next to the Discourse logo on desktop browsers).

For me, it really impacts functionality since you cannot close the shoutbox by clicking outside - and you cannot scroll the main page any more, just Babble.

**Comment by gdpelican** [comment] 2017-03-21 20:28
Great! Thanks for that. I'll have a go tomorrow to see if I can get this
sorted.

**Comment by gdpelican** [comment] 2017-03-29 22:53
This should now be fixed in the beta branch, and I'm going to merge into master later today.

**Closed by gdpelican** 2017-03-29 22:53 UTC

**Comment by levidurfee** [comment] 2020-11-02 15:09
Which commit was merged to fix this?
