### ISSUE TITLE
Timestamps show “invalid date” in Safari+Firefox

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#3] opened 2015-08-04 17:44 UTC
This is an issue I only came across in Safari:
![bildschirmfoto 2015-08-04 um 19 41 20](https://cloud.githubusercontent.com/assets/9109505/9067995/f827afb0-3ae0-11e5-8ae6-6fe149a7aa58.png)
These disappear after a reload, the generated HTML reads as follows:

    <span class="relative-date" title="Invalid date" data-time="NaN" data-format="tiny">Invalid date</span>

**Comment by JSey** [comment] 2015-08-06 19:47
Update: happens in Firefox, too. Could this be a locale issue?

**Comment by gdpelican** [comment] 2015-08-06 20:08
I'm a little confused by this error, because it shouldn't be any different
than however Discourse does it with their posts.

It's line 28 in `templates/components/babble-post.hbs`:

{{age-with-tooltip post.created_at}}

Seems like the two possibilities would be
a) there's a bug in the existing age-with-tooltip directive in Discourse
b) post.created_at is being serialized out as null / NaN / something weird
for some reason once the post has first been created

of which b seems more likely (but I can't fathom why at the moment.)

**Comment by gdpelican** [comment] 2015-08-12 18:58
I've tracked this down a little bit; turns out the date format which is being serialized out from the server
```
"2015-08-12 18:02:44 UTC"
```

doesn't match the ones on existing posts
```
"2015-08-12T16:40:40.161Z"
```

And so calling `new Date(post.created_at)` returns an invalid date, because it can't parse that date format correctly. (Not sure why it works in chrome ¯\_(ツ)_/¯)

The quick fix to is just jigger the timestamps we have into the timestamps we need, but I'd kinda rather get to the root of the problem instead (ie, the Discourse mothership is applying some transformation to the posts that come back, that we're not applying.)

Will take a little more research to figure out the root cause, but figured I'd share in case anyone had any insight.

**Comment by JSey** [comment] 2015-08-16 18:01
Been trying to dig into this - but I'm a bit lost. Looks like I can't find any crucial differences… Am I right that after posting, ```respond_with_topic_view``` gets called? Mothership seems to like ```render_json_dump``` better than render json: - but that does not seem to make any difference?!

**Comment by gdpelican** [comment] 2015-08-16 18:19
Yeah, I'm a bit confounded as well. The idea behind the architecture is 'call an endpoint, then use Discourse.Babble.refresh as a callback, always.' That way we don't have differences in the way read, show, or post update the client side. ( Except we do, since 'show' and 'post' seem to be behaving differently (╯°□°）╯︵ ┻━┻ )

No time to do a code dive right this second, but there must be either some difference in how `respond_with_topic_view` is handling in show vs read; maybe the fact that it's coming through message bus is making a difference somehow.

**Comment by gdpelican** [comment] 2015-08-18 18:36
Should be fixed with #23

**Closed by gdpelican** 2015-08-18 18:36 UTC

**Comment by ebolyen** [comment] 2018-03-29 15:05
Hello, 
I'm seeing this again in Firefox:
![image](https://user-images.githubusercontent.com/3976804/38096437-e0984642-3340-11e8-85db-6c68756715ec.png)

It looks like `"UTC"` is getting dumped back into the `post.created_at`. The times correct themselves when you refresh.
